-- Seed exécuté après les migrations Supabase lors de `supabase db reset`.
-- Le schéma des tables est géré par Prisma (appliqué juste après via
-- `prisma migrate deploy`) ; le seed SQL Supabase est donc volontairement vide.
-- Les données de démonstration se chargent avec `pnpm db:seed:demo`.
